### ISSUE TITLE
Poe Procurement не грузит сундук с закладками

### ISSUE THREAD

**Issue by Minchanin** [medvedttn/Procurement#1]
[31-05-2015 12:33] System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в POEApi.Model.Map..ctor(Item item)
   в POEApi.Model.ItemFactory.Get(Item item)
[31-05-2015 12:33] ItemFactory unable to instanciate type : Карта фруктового сада
[31-05-2015 12:33] Error downloading stash for Одна жизнь, exception details: System.Exception: ItemFactory unable to instanciate type : Карта фруктового сада
   в POEApi.Model.ItemFactory.Get(Item item)
   в System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в POEApi.Model.Stash..ctor(Stash proxy)
   в POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   в POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   в POEApi.Model.POEModel.GetStash(String league)
[31-05-2015 12:33] System.Exception: Downloading stash for Одна жизнь, details logged to DebugInfo.log, please open a ticket at https://github.com/medvedttn/Procurement/issues
   в POEApi.Model.POEModel.GetStash(String league)
   в Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   в Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   в System.Threading.Tasks.Task.Execute()

**Comment by Minchanin** [comment]
[31-05-2015 12:40] System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в POEApi.Model.Map..ctor(Item item)
   в POEApi.Model.ItemFactory.Get(Item item)
[31-05-2015 12:40] ItemFactory unable to instanciate type : Карта фруктового сада
[31-05-2015 12:40] Error downloading stash for Одна жизнь, exception details: System.Exception: ItemFactory unable to instanciate type : Карта фруктового сада
   в POEApi.Model.ItemFactory.Get(Item item)
   в System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в POEApi.Model.Stash..ctor(Stash proxy)
   в POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   в POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   в POEApi.Model.POEModel.GetStash(String league)
[31-05-2015 12:40] System.Exception: Downloading stash for Одна жизнь, details logged to DebugInfo.log, please open a ticket at https://github.com/medvedttn/Procurement/issues
   в POEApi.Model.POEModel.GetStash(String league)
   в Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   в Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   в System.Threading.Tasks.Task.Execute()

**Comment by Minchanin** [comment]
Когда начинает чекать перса/сундук где лежат "Карта фруктового сада" все сразу останавливается.

**Comment by medvedttn** [comment]
Странно, строка "Карта фруктового сада" есть в типах карт в Data_RU.xml...
Через сайт в профиле персонажа этот сундук с картой в табе отображается нормально?
Есть ли во всплывающем тексте карты:
1) Тип предмета - строка "Карта"?
2) В тексте описания - "Перейдите на эту карту"?

**Comment by Minchanin** [comment]
Да на сайте у меня все карты в одной табе "2", и на любую карту программа так же реагирует. Артизи фрагменту норм, а вот карты никак, как бы я их не перекладывал или не апгрейдил

**Comment by medvedttn** [comment]
Внимательнее прочитайте мой вопрос - пункты 1) и 2). Можно сделать скриншот всплывающей информации о карте.
"Артизи фрагменту" - это вообще непонятно что написано).

**Comment by MaxvelDrey** [comment]
Аналогичная проблема. Карта на сайте отображается нормально в сундуке. Скрин прилагаю.
На счет "Атзири фрагмента" (ясно ведь что опечатался человек в названии), он наверное имеет ввиду осколки "Жертв". (полдень/полночь/рассвет/закат)

Текст из дебаг-файла:

[02-06-2015 12:41] System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в POEApi.Model.Map..ctor(Item item)
   в POEApi.Model.ItemFactory.Get(Item item)
[02-06-2015 12:41] ItemFactory unable to instanciate type : Карта склепа
[02-06-2015 12:41] Error downloading stash for Стандарт, exception details: System.Exception: ItemFactory unable to instanciate type : Карта склепа
   в POEApi.Model.ItemFactory.Get(Item item)
   в POEApi.Model.Stash.<.ctor>b__0(Item item)
   в System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в POEApi.Model.Stash..ctor(Stash proxy)
   в POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   в POEApi.Model.POEModel.GetStash(String league)
[02-06-2015 12:41] System.Exception: Downloading stash for Стандарт, details logged to DebugInfo.log, please open a ticket at https://github.com/medvedttn/Procurement/issues
   в POEApi.Model.POEModel.GetStash(String league)
   в Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   в Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()

![default](https://cloud.githubusercontent.com/assets/2778421/7933045/0701c6a8-0925-11e5-978d-712d0d77a8e0.png)

**Comment by MaxvelDrey** [comment]
Я тут залез немного в файл перевода и оригинальный дата (оба из папки прокурмента), и обнаружил одну странность... Может дело в ней.
В файле оригинала последней картой в списке числится "Palace Map".
А в файле перевода, последней числится "Карта храма ваал".
Необходимый же перевод последней карты из оригинала, в файле перевода находится предпоследним "Карта дворца".

Может проблема кроется где-то в этих нестыковках. Все строки проверять не стал, т.к. не на столько дружу с англ. что бы знать переводы каждого названия, но раз есть один косяк, то могут быть и другие.

**Comment by ArFluTsoyOLD** [comment]
Ещё с пристанью подобное, судя по всему. Думаете это из-за несовпадений в переводе для наших серверов?

Procurement 1.9.3.3 Medved Edition Initialized.
                                          
Authenticating                                                                            [OK]
Logged as <SessionID used>                                                                
Loading characters...                                                                     [OK]
Loading Стандарт Stash Tab 1...                                                           [OK]
Loading Стандарт Stash Tab 2...                                                           [OK]
Loading Стандарт Stash Tab 3...                                                           [OK]
Loading Стандарт Stash Tab 4...                                                           [OK]
Loading Стандарт Stash Tab 5...                                                           [OK]

[Error] Downloading stash for Стандарт, details logged to DebugInfo.log, please open a ticket at https://github.com/medvedttn/Procurement/issues

[03-06-2015 10:43] ItemFactory unable to instanciate type : Карта пристани
[03-06-2015 10:43] Error downloading stash for Стандарт, exception details: System.Exception: ItemFactory unable to instanciate type : Карта пристани
   в POEApi.Model.ItemFactory.Get(Item item)
   в POEApi.Model.Stash.<.ctor>b__0(Item item)
   в System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в POEApi.Model.Stash..ctor(Stash proxy)
   в POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   в POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   в POEApi.Model.POEModel.GetStash(String league)
[03-06-2015 10:43] System.Exception: Downloading stash for Стандарт, details logged to DebugInfo.log, please open a ticket at https://github.com/medvedttn/Procurement/issues
   в POEApi.Model.POEModel.GetStash(String league)
   в Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   в Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()

**Comment by medvedttn** [comment]
Отсутствовала строка в ресурсах "Уровень карты". Обновил релиз, проверяйте.

**Comment by ArFluTsoyOLD** [comment]
Заработало. Всё чудно и круто. Большое спасибо за проделанный труд! Ждём Апдейтов с дружелюбным русским языком)

P.S.:Совсем идеальным развитием событий было бы нахождение кодера на мобильные платформы, с последующим выпуском приложения. Хотя, думаю, вы и сами о подобном думали

**Comment by MaxvelDrey** [comment]
Плюсую. Работает нормально, но очень неудобно с англ. локализацией. Русские предметы - в данном случае не приносят никакого профита, т.к. по сути открывая прогу, большинство уже знают что хотят продать и где оно лежит. А вот англ. интерфейс - доставляет массу неудобств тем кто не дружен с англ. языком ;)
