### ISSUE TITLE
Вылеты

### ISSUE THREAD

**Issue by gBaH0JI9I** [medvedttn/Procurement#10]
Программа непредсказуемо крашится.
Несколько раз при выборе вкладки "рецепты" в лиге Отряды. Потом открыло. Последний вылет на рецептах лиги "стандарт". Зависла и вылетела.

[23-08-2015 3:43] Application Version: Procurement 1.9.9
[23-08-2015 3:43] 
CurrentCulture: ru-RU
CurrentUICulture: ru-RU
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: Отряды

[23-08-2015 3:43] System.ArgumentNullException: Ссылка на строку не ссылается на экземпляр String.
Имя параметра: s
   в Procurement.Utility.StashHelper.buildImage(Tab tab, List`1 images, Bitmap finalImage, Int32 offset, String key)
   в Procurement.Utility.StashHelper.GenerateTabImage(Tab tab, Boolean mouseOver)
   в Procurement.View.TabIDToStashControlFiltered.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   в System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   в System.Windows.Data.BindingExpression.Activate(Object item)
   в System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   в System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   в MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   в MS.Internal.Data.DataBindEngine.Run(Object arg)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[23-08-2015 3:58] Application Version: Procurement 1.9.9
[23-08-2015 3:58] 
CurrentCulture: ru-RU
CurrentUICulture: ru-RU
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: Стандарт

[23-08-2015 3:58] System.ArgumentNullException: Ссылка на строку не ссылается на экземпляр String.
Имя параметра: s
   в Procurement.Utility.StashHelper.buildImage(Tab tab, List`1 images, Bitmap finalImage, Int32 offset, String key)
   в Procurement.Utility.StashHelper.GenerateTabImage(Tab tab, Boolean mouseOver)
   в Procurement.View.TabIDToStashControlFiltered.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   в System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   в MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   в MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView)
   в MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   в System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   в System.Windows.WeakEventManager.DeliverEventToList(Object sender, EventArgs args, ListenerList list)
   в System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   в Procurement.Controls.RecipeResults.RadioButton_Checked(Object sender, RoutedEventArgs e)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   в System.Windows.Controls.RadioButton.OnChecked(RoutedEventArgs e)
   в System.Windows.Controls.Primitives.ToggleButton.OnIsCheckedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   в System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   в System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   в System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   в System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   в System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   в System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   в System.Windows.Controls.Primitives.ToggleButton.OnClick()
   в System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   в System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   в System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   в System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   в System.Windows.Input.InputManager.ProcessStagingArea()
   в System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   в System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   в System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by medvedttn** [comment]
Вылетает в каком режиме (оффлайн, онлайн?). Пробуйте удалить папку "NoEmail" и зайти онлайн.

**Comment by gBaH0JI9I** [comment]
Вылетает в режиме "Онлайн" В офлайне я его не запускал ни разу даже.
Только что попробовал снова на рабочем компе, удалил папку "NoEmail" - результата нет, вылетает окно об ошибке при переходе на вкладку рецепты в лиге Отряды.
Лог уже с этой машины 

[24-08-2015 13:16] Application Version: Procurement 1.9.9
[24-08-2015 13:16] 
CurrentCulture: ru-RU
CurrentUICulture: ru-RU
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1
Current League: Отряды

[24-08-2015 13:16] System.ArgumentNullException: Ссылка на строку не ссылается на экземпляр String.
Имя параметра: s
   в Procurement.Utility.StashHelper.buildImage(Tab tab, List`1 images, Bitmap finalImage, Int32 offset, String key)
   в Procurement.Utility.StashHelper.GenerateTabImage(Tab tab, Boolean mouseOver)
   в Procurement.View.TabIDToStashControlFiltered.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   в System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   в System.Windows.Data.BindingExpression.Activate(Object item)
   в System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   в System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   в MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   в MS.Internal.Data.DataBindEngine.Run(Object arg)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by gBaH0JI9I** [comment]
Добавлю...
Если при запуске программы вначале зайти в рецепты на лиге стандарт, то и в лиге отряды рецепты открываются.
Если же сразу после запуска идти в рецепты Отрядов, не открывая рецепты стандарта - вылет.
