### ISSUE TITLE
Не работает на вин 8.1

### ISSUE THREAD

**Issue by vice-versa** [medvedttn/Procurement#2]
Релиз 5.1 на работает на 8.1 выбираешь гарену, вводишь куку,нажимаешь логин. Программа зависает. При этом ошибок не выдает. В терминале пишет Procurement 1.9.5.1 Medved Edition Initialized.

**Comment by medvedttn** [comment]
Проверьте настройки firewall'а (возможно блочит встроенный в Windows). Возможно перегружены серверы Гарены(при моей проверке на win8.1 каждая картинка грузилась по 2-5 сек).
Пробуйте подождать 2 мин после логина, хотя таймауты передачи/приема установлены на 10сек(в 1.9.5.1).

**Comment by medvedttn** [comment]
Увеличил время ожидания в версии 1.9.6 для форума до 60сек, прочее  - 30сек.

**Comment by vice-versa** [comment]
Спасибо, 1.6.1 работает
