### ISSUE TITLE
Тэги шаблона форума

### ISSUE THREAD

**Issue by gBaH0JI9I** [medvedttn/Procurement#3]
Версия 1.9.6.1
Не работают некоторые тэги в фаблоне форума. В шаблоне тэги прописаны, но на вкладке "Экспорт на форум" ссылки не отображаются, хотя вещи есть. И в магазин, соответственно, они не грузятся.
Например, вот эти точно не работают:

[spoiler="          Aura Gems          "]
{AuraGems}
[/spoiler]
[spoiler="          Curse Gems          "]
{CurseGems}
[/spoiler]
[spoiler="          Support Gems          "]
{SupportGems}
[/spoiler]
[spoiler="          Vaal Gems          "]
{VaalGems}
[/spoiler]

Насчет этих не совсем уверен:

[spoiler="          Daggers          "]
{RareDagger}
[/spoiler]
[spoiler="          Claws          "]
{RareClaw}
[/spoiler]
[spoiler="          Bows  & Quivers          "]
{RareBow}
{RareQuiver}
[/spoiler]

**Comment by medvedttn** [comment]
Я конечно подумаю как бы это сделать, но такие штуки с перемешкой рус-англ:
[spoiler="          Камни проклятий          "]
{ПроклятьеGems}
[/spoiler]

точно делать не буду.

**Comment by gBaH0JI9I** [comment]
Перемешку и не надо. Я сам за то, чтобы переменные были на одном языке. Унификация, иначе можно запутаться.
Но проблема есть и исправлять ее надо, потому что это баг программы. Она не работает так как надо.
Ну или на крайний случай, скажи в какую сторону копать, какие файлы за это отвечают в исходниках, я сам себе поправлю через костыли или еще как и скомпилирую.
Но надеюсь все же, что проблема решится.

**Comment by medvedttn** [comment]
Камни вроде пофиксил(по крайней мере в магазине все показывает) в 1.9.7
Начет тега "Rarity""GearType" вроде и так все работает, там базовые типы для RU забиты изначально в XML Data_RU и подгружаются в конструкторе класса.

**Comment by gBaH0JI9I** [comment]
Спасибо большое, тэги работают прекрасно. Теперь все как надо.

У меня еще вопрос только возник: во вкладке "Экспорт на форум" есть выпадающее меню с выбором файла шаблона выгрузки. Там выбран один единственный, входящий в комплект файл "ForumExportTemplate.txt"
Можно ли самомму добавить в этот список еще шаблонов? Пробовал создавать txt-файл, просто копию, программа его игнорирует, видит только родной.
Или выбрать нельзя? Но зачем тогда выпадающее поле?

P.S. Все, вопрос снят, сам нашел, нужно курить вручную настройки в файле  "Settings.xml"

Еще раз спасибо за программу и быстрое исправление.
