### ISSUE TITLE
Сохранение параметров "Настройки торговли"

### ISSUE THREAD

**Issue by vice-versa** [medvedttn/Procurement#4]
При первой попытке сохранить параметры торговли, если не ввести параметр "Заголовок темы". Невнятно ругается ссылаясь на файл лога. Необходимо либо установить там значение по умолчанию. либо ругаться конкретно на этот параметр. Заранее спасибо если реализуете.

**Comment by medvedttn** [comment]
Сохраняется пустое значение в настройках, вот и ругается. Пускай лучше здесь, чем если ввести пустую строку "" будет потом "ругаться" при обновлении/апе темы.
Для двух входных параметров не вижу смысла делать для каждого свою обработку исключения, тем более визуально видно, какое поле ввода не заполнено.

И вообще заполнять реальные требуемые значения для idТемы/Названия пустыми значениями (при которых настройки сохранятся без ошибок, но торговля работать не будет) как то странно...

**Comment by vice-versa** [comment]
Смысл не в том чтобы сохранять пустые значения.

Если бы я делал форму я бы сделал так:
1. Пометил бы на форме поля например звездочкой, обязательные для заполнения.
2. Внизу вывел бы подсказку, что поля помеченные звездочкой обязательные.
3. При ошибке сохранения ругался бы не иди туда не знаю куда найди лог да еще и открой его, особенно это плохо когда ты поставил через инсталлер и вообще не знаешь в какой папке стоит у тебя прога.
4. Вместо "иди посмотри что в логе". Ругался бы ошибкой из лога. А лучше всего бы написал свой обработчик который ошибки из лога переводил бы на язык пользователя. Например 
"Ты на заполнил следующие обязательный поля", или "Идентификатор темы может состоять только из цифр".
4. Профит!

По моему, это упростит работу пользователям. Но это скорее не бага, а пожелание на юзабилити.
Спасибо за внимание.
