### ISSUE TITLE
Поддержка новых лиг

### ISSUE THREAD

**Issue by gBaH0JI9I** [medvedttn/Procurement#5]
[Ошибка] Downloading stash for Отряды, details logged to DebugInfo.log, please open a ticket at https://github.com/medvedttn/Procurement/issues

**Comment by ArFluTsoyOLD** [comment]
Downloading stash for Стандарт, details logged to DebugInfo.log, please open a ticket at https://github.com/medvedttn/Procurement/issues

Стандарт тоже отказывается прогружать стеш

**Comment by medvedttn** [comment]
Лиги тут не при чем. Добавили параметр в HTTS запрос. И вы хоть логи (файл DebugInfo.log, на заданной временной метке) выкладывайте, что ли.

**Comment by medvedttn** [comment]
Обновил версию до 1.9.8, проверяйте.

**Comment by gBaH0JI9I** [comment]
Все хорошо. Спасибо.
