### ISSUE TITLE
Ошибка при загрузке персонажей

### ISSUE THREAD

**Issue by svazz** [medvedttn/Procurement#7]
Аутентификация                                                                            [OK]
Аккаунт <img class="achievement" src="/image/icons/achievements/1.png?v=4" alt="Completed 1 Challenge" title="Completed 1 Challenge" />Svazzz
Загрузка персонажей...                                                                    

[Ошибка] Ожидается состояние "Element".. Обнаружен "Text" с именем "", пространство имен "". 

![debuginfo log](https://cloud.githubusercontent.com/assets/13511045/8895465/6b88fb2a-33e4-11e5-8e70-7f54a2505880.png)

**Comment by medvedttn** [comment]
Файлы не-изображений нельзя прикладывать вроде(лог это текстовый файл). Достаточно вставить текст.
У вас в личном кабинете (http://web.poe.garena.ru/my-account) так и пишеться "Completed 1 Challenge Svazzz" или там раздельно HTML ссылка а потом имя аккаунта?
Просьба сохранить эту страницу как HTML и выложить сюда код HTML.

**Comment by dor003** [comment]
`<div class="statusBarCenter"></div><div class="statusBarRight"></div><div class="row1"><span class="statusItem loggedInStatus">Вошли как <span class="profile-link achieved" ><a href="/account/view-profile/username"><img class="achievement" src="/image/icons/achievements/1.png?v=4" alt="Completed 1 Challenge" title="Completed 1 Challenge" />username</a></span></span>         <a href="http://shop.poe.garena.ru/" class="statusItem purchaseLink"><span class="coins"><span class="amount shopCurrentCoinValue account">0</span><span class="label shopHideDuringReload"></span></span><span class="pointsIcon"></span></a></div>`

**Comment by dor003** [comment]
Фикс: HttpTransport.cs:143

```
string regexp_pattern = @"\<a href=""/account/view-profile/(?<accname>.+?)""\>";
```

**Comment by medvedttn** [comment]
Из ссылки href лучше не брать, там могут быть URLEncoded закодированы UTF символы (а-ля "ä").Нужна 2я часть username - которая может быть с доп. тегом img .../>

**Comment by dor003** [comment]
Тогда предложу такой вариант:

```
string regexp_pattern = @"\<a href=""/account/view-profile/.*?\>(?(\<img).*\/>)(?<accname>.+?)\<\/a\>";
```

**Comment by medvedttn** [comment]
Обновил до 1.9.8.2.
