### ISSUE TITLE
[Ошибка] Удаленный сервер возвратил ошибку: (500) Внутренняя ошибка сервера.

### ISSUE THREAD

**Issue by riddick927** [medvedttn/Procurement#9]
Выбираю гарену ввожу ид сессии который был сказан здесь 
https://web.poe.garena.ru/forum/view-thread/1606/page/1
 и пишет вот такую ошибку. 
[Ошибка] Удаленный сервер возвратил ошибку: (500) Внутренняя ошибка сервера.

**Comment by medvedttn** [comment]
Лаги интернета/задержки серверов на стороне GGG/Garena.
Возможно ID сессии устарел, перелогиньтесь на форуме.
